/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './pagination.module';
import * as import2 from '@angular/common';
class PaginationModuleInjector extends import0.ɵNgModuleInjector<import1.PaginationModule> {
  _CommonModule_0:import2.CommonModule;
  _PaginationModule_1:import1.PaginationModule;
  __NgLocalization_2:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  createInternal():import1.PaginationModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._PaginationModule_1 = new import1.PaginationModule();
    return this._PaginationModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.PaginationModule)) { return this._PaginationModule_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const PaginationModuleNgFactory:import0.NgModuleFactory<import1.PaginationModule> = new import0.NgModuleFactory<any>(PaginationModuleInjector,import1.PaginationModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3ZrbmFiZWwvRGV2ZWxvcGVyL0Btb2xlY3VsZS9wYWdpbmF0aW9uL3NyYy9wYWdpbmF0aW9uLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy92a25hYmVsL0RldmVsb3Blci9AbW9sZWN1bGUvcGFnaW5hdGlvbi9zcmMvcGFnaW5hdGlvbi5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
